---
- git: repo={{ agent_repo }}
       dest={{ agent_directory }}
       version={{ agent_branch }}
       recursive=yes
       force=yes
- command: make chdir={{ agent_directory }}
- command: make package chdir={{ agent_directory }}
