---
## Apt
- command: add-apt-repository --yes ppa:kalakris/cmake
  when: ansible_pkg_mgr == 'apt'
- apt: upgrade=dist update_cache=yes
  when: ansible_pkg_mgr == 'apt'
- apt: name={{ item }} state=present
  when: ansible_pkg_mgr == 'apt'
  with_items:
    - reprepro
    - git-core
    - devscripts
    - debhelper
    - build-essential
    - cmake
    - vim
## Yum
- yum: name=* state=latest
  when: ansible_pkg_mgr == 'yum'
- yum: name={{ item }} state=latest
  when: ansible_pkg_mgr == 'yum'
  with_items:
    - '@Development\ tools'
    - git
    - createrepo
    - gcc-c++
    - rpm-build
    - cmake
    - vim
